export const compsDir = {
  HOME: "home/",
  INFO: "info/",
  SETTINGS: "settings/",
  AUTH: "auth/",
  SEARCH: "search/",
  PROFILE: "profile/",
  ADMIN_MIX: "admin/mixin/",
  ADMIN_BAN: "admin/ban/",
  ADMIN_ROLES: "admin/roles/",
  AED_DEVICE: "device/",
  NEWS: "news/",
  AED_EVENT: "aed/event/",
  AED_HISTORY: "aed/history/",
  AED_PROBLEMS: "aed/problems/"
};

export const comps = {
  HOME: compsDir.HOME + "HomeCard",
  INFO: compsDir.INFO + "InfoCard",
  SETTINGS: compsDir.SETTINGS + "SettingsCard",
  SYS_ADMIN: compsDir.AUTH + "SysAdminCard",
  REGISTER: compsDir.AUTH + "RegistrationCard",
  LOGIN: compsDir.AUTH + "LoginCard",
  SEARCH: compsDir.SEARCH + "SearchCard",
  PROFILE: compsDir.PROFILE + "ProfileCard",
  PROFILE_EDIT: compsDir.PROFILE + "EditProfileCard",
  PROFILE_PRIVACY: compsDir.PROFILE + "PrivacySettingsCard",
  ADMIN_MIX: compsDir.ADMIN_MIX + "AdminMixinCard",
  ADMIN_R_CH: compsDir.ADMIN_ROLES + "RolesChangeCard",
  ADMIN_R_AD: compsDir.ADMIN_ROLES + "RolesAddCard",
  ADMIN_R_DE: compsDir.ADMIN_ROLES + "RolesDelCard",
  ADMIN_BAN: compsDir.ADMIN_BAN + "BanUsersCard",
  ADMIN_UNBAN: compsDir.ADMIN_BAN + "UnbanUsersCard",
  AED_REG: compsDir.AED_DEVICE + "RegisterAedDeviceCard",
  AED_INFO: compsDir.AED_DEVICE + "AedDeviceInfoCard",
  AED_EDIT: compsDir.AED_DEVICE + "AedDeviceEditCard",
  NEWS_SEARCH: compsDir.NEWS + "NewsSearchCard",
  NEWS_CREATE: compsDir.NEWS + "NewsCreate",
  NEWS_ALL: compsDir.NEWS + "NewsAllCard",
  NEWS_MORE: compsDir.NEWS + "NewsMoreCard",
  AED_EVENT: compsDir.AED_EVENT + "AedEventCard",
  AED_EV_CR: compsDir.AED_EVENT + "AedEventCreateCard",
  AED_EV_MORE: compsDir.AED_EVENT + "EventMoreCard",
  AED_EV_CH: compsDir.AED_EVENT + "AedEventChannelCard",
  AED_EV_LIVE: compsDir.AED_EVENT + "EventLiveCard",
  AED_HISTORY: compsDir.AED_HISTORY + "HistoryCard",
  AED_EV_LIST: compsDir.AED_EVENT + "EventListCard",
  AED_PR_CR: compsDir.AED_PROBLEMS + "ProblemsCreateCard",
  AED_PR_LIST: compsDir.AED_PROBLEMS + "ProblemsListCard",
  AED_PR_MORE: compsDir.AED_PROBLEMS + "ProblemsMoreCard",
};
